USE StarSchema

ALTER TABLE Orders
ADD CONSTRAINT FK_ORDERS_CUSTOMER
FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID);

ALTER TABLE Orders
ADD CONSTRAINT FK_ORDERS_DATE
FOREIGN KEY (DateID) REFERENCES [Date](DateID);

ALTER TABLE Orders
ADD CONSTRAINT FK_ORDERS_EMPLOYEE
FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID);

ALTER TABLE Orders
ADD CONSTRAINT FK_ORDERS_PRODUCT
FOREIGN KEY (ProductID) REFERENCES Dim_Product(ProductID);

ALTER TABLE Orders
ADD CONSTRAINT FK_ORDERS_STORE
FOREIGN KEY (StoreID) REFERENCES Dim_Store(StoreID);